apiVersion: v1
kind: Secret
metadata:
  name: backstage-sa-token
  namespace: default  # Change if using another namespace
  annotations:
    kubernetes.io/service-account.name: "backstage-sa"
type: kubernetes.io/service-account-token
